# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DatabaseStudiesController do

  # This should return the minimal set of attributes required to create a valid
  # DatabaseStudy. As you add validations to DatabaseStudy, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DatabaseStudiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all database_studies as @database_studies" do
      database_study = DatabaseStudy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:database_studies).should eq([database_study])
    end
  end

  describe "GET show" do
    it "assigns the requested database_study as @database_study" do
      database_study = DatabaseStudy.create! valid_attributes
      get :show, {:id => database_study.to_param}, valid_session
      assigns(:database_study).should eq(database_study)
    end
  end

  describe "GET new" do
    it "assigns a new database_study as @database_study" do
      get :new, {}, valid_session
      assigns(:database_study).should be_a_new(DatabaseStudy)
    end
  end

  describe "GET edit" do
    it "assigns the requested database_study as @database_study" do
      database_study = DatabaseStudy.create! valid_attributes
      get :edit, {:id => database_study.to_param}, valid_session
      assigns(:database_study).should eq(database_study)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DatabaseStudy" do
        expect {
          post :create, {:database_study => valid_attributes}, valid_session
        }.to change(DatabaseStudy, :count).by(1)
      end

      it "assigns a newly created database_study as @database_study" do
        post :create, {:database_study => valid_attributes}, valid_session
        assigns(:database_study).should be_a(DatabaseStudy)
        assigns(:database_study).should be_persisted
      end

      it "redirects to the created database_study" do
        post :create, {:database_study => valid_attributes}, valid_session
        response.should redirect_to(DatabaseStudy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved database_study as @database_study" do
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseStudy.any_instance.stub(:save).and_return(false)
        post :create, {:database_study => {}}, valid_session
        assigns(:database_study).should be_a_new(DatabaseStudy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseStudy.any_instance.stub(:save).and_return(false)
        post :create, {:database_study => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested database_study" do
        database_study = DatabaseStudy.create! valid_attributes
        # Assuming there are no other database_studies in the database, this
        # specifies that the DatabaseStudy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DatabaseStudy.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => database_study.to_param, :database_study => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested database_study as @database_study" do
        database_study = DatabaseStudy.create! valid_attributes
        put :update, {:id => database_study.to_param, :database_study => valid_attributes}, valid_session
        assigns(:database_study).should eq(database_study)
      end

      it "redirects to the database_study" do
        database_study = DatabaseStudy.create! valid_attributes
        put :update, {:id => database_study.to_param, :database_study => valid_attributes}, valid_session
        response.should redirect_to(database_study)
      end
    end

    describe "with invalid params" do
      it "assigns the database_study as @database_study" do
        database_study = DatabaseStudy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseStudy.any_instance.stub(:save).and_return(false)
        put :update, {:id => database_study.to_param, :database_study => {}}, valid_session
        assigns(:database_study).should eq(database_study)
      end

      it "re-renders the 'edit' template" do
        database_study = DatabaseStudy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseStudy.any_instance.stub(:save).and_return(false)
        put :update, {:id => database_study.to_param, :database_study => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested database_study" do
      database_study = DatabaseStudy.create! valid_attributes
      expect {
        delete :destroy, {:id => database_study.to_param}, valid_session
      }.to change(DatabaseStudy, :count).by(-1)
    end

    it "redirects to the database_studies list" do
      database_study = DatabaseStudy.create! valid_attributes
      delete :destroy, {:id => database_study.to_param}, valid_session
      response.should redirect_to(database_studies_url)
    end
  end

end
